### ISSUE TITLE
目前的比如说sum之类的函数不支持么？

### ISSUE THREAD

**Issue by LoganLai** [wolfhong/grafana-openfalcon-datasource#2]
您好，
请教一下目前不支持别名聚合之类的函数么？

**Comment by wolfhong** [comment]
@LoganLai  是的。该项目fork自 open-falcon/grafana-openfalcon-datasource 修复了一些bug, 并未增加新功能，因此没有sum之类的聚合函数支持。

**Comment by LoganLai** [comment]
明白了，感谢~
